name: "CD pipeline"

on:
  workflow_run:
    workflows: 
      - "Simple React CI Pipeline / Workflow"  # Ensure this matches the triggering workflow's name
    types:
      - completed
  workflow_dispatch:

jobs: 
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: "Setup Vercel CLI"
        run: npm install -g vercel

      - name: "List Artifacts (Debugging)"
        run: gh api repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[] | {name: .name, id: .id}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Download Build Files"
        uses: actions/download-artifact@v3
        with:
          name: build  # Ensure this matches the artifact name in the CI workflow
          path: ./build # Optional: Specify where to save the artifact

      - name: "Deploy to Vercel"
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --name=cicdproject
