name: "CD pipeline"

on:
  workflow_run:
    workflows: 
      - "Simple React CI Pipeline / Workflow"  # Matches the CI workflow name
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Debug: List available artifacts
      - name: "List Artifacts (Debugging)"
        run: gh api repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[] | {name: .name, id: .id}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Download the build artifact
      - name: "Download Build Files"
        uses: actions/download-artifact@v4
        with:
          name: build  # Matches the artifact name in the CI workflow
          path: dest # Optional: Specify where to extract the artifact

      # Deploy to Vercel
      - name: "Deploy to Vercel"
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm
