name: "CD pipeline"

on:
  workflow_run:
    workflows: 
      - "Simple React CI Pipeline / Workflow"
    types:
      - completed
  workflow_dispatch:

jobs: 
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code (optional if needed)
        uses: actions/checkout@v3

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: "Setup Vercel CLI"
        run: npm install -g vercel

      - name: "Download Build Files"
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: "Deploy to Vercel"
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --name=cicdproject
