name: "Simple React CI Pipeline / Workflow"

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: "Checkout Code"
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '16' # Specify the Node.js version

      - name: "Check Node.js version"
        run: node --version

      # Step 3: Install dependencies
      - name: "Install Dependencies"
        run: npm install
       

      # Step 4: List files (for debugging purposes)
      - name: "List Directory"
        run: ls 
        

      # Step 5: Run tests
      - name: "Run Tests"
        run: npm test 

      # Step 6: Build the React application (optional)
      - name: "Run bulid"
        run: npm run build

      - name: "uplode  product-ready build files"
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist

