name: "Simple React CI Pipeline / Workflow"

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: "Checkout Code"
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: "Install Dependencies"
        run: npm install

      # Step 4: Build the React application
      - name: "Build React App"
        run: npm run build

      # Step 5: Verify the build directory (debugging)
      - name: "List Build Directory"
        run: ls -l build

      # Step 6: Upload product-ready build files
      - name: "Upload Product-Ready Build Files"
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build  # Ensure this is the correct build directory
