name: "Simple React CI Pipeline / Workflow"

on:
  push:
    branches:
      - main
      - master
#   pull_request: # Optional: Trigger workflow for PRs
#     branches:
#       - main
#       - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
    #   - name: "Checkout Code"
    #     uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: "Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the Node.js version
      - name: "Check node version"
        run: node --version
      - name: "Clone The Repository"
        uses: actions/setup-node@v2 
      # Step 3: Install dependencies
      - name: "Install Dependencies"
        run: npm install

    #   # Step 4: Run tests
    #   - name: "Run Tests"
    #     run: npm test -- --watchAll=false

    #   # Step 5: Build the React application (optional)
    #   - name: "Build Project"
    #     run: npm run build
